name: build

on:
  workflow_call:
    inputs:
      dockerRepository: # docker image repository
        required: true
        type: string
      githubContext: # github context in JSON format
        required: true
        type: string
      appName: # todo set appname to default to something like presentation or whatever
        required: true
        type: string
      selfContained:
        required: false
        type: boolean
        default: true
      baseImage:
        required: false
        type: string
        default: 7.0-alpine
    secrets:
      PAT: # github personal access token
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  initialize:
    name: initialize
    runs-on: ubuntu-latest
    outputs:
      dockerTag: ${{ steps.initialize.outputs.dockerTag }}
      branch: ${{ steps.initialize.outputs.branch }}
    steps:
    -
      name: Set github context
      run: |
        echo 'githubRepository=${{ fromJSON(inputs.githubContext).repository }}' >> $GITHUB_ENV
        echo 'githubSha=${{ fromJSON(inputs.githubContext).sha }}' >> $GITHUB_ENV
        echo 'githubRef=${{ fromJSON(inputs.githubContext).ref }}' >> $GITHUB_ENV
        echo 'githubHeadRef=${{ fromJSON(inputs.githubContext).head_ref }}' >> $GITHUB_ENV
        echo 'pullRequestNumber=${{ fromJSON(inputs.githubContext).event.pull_request.number }}' >> $GITHUB_ENV
    -
      name: Initialize build info
      id: initialize
      run: |
        githubHeadRef=${{ env.githubHeadRef }}
        dockerTag=""

        # enable case insensitive regex
        # shopt -s nocasematch
        # mainPattern='refs\/heads\/(main)'

        # check if this is a PR or not
        if [[ $githubHeadRef == "" ]]; then
          # this run is for the main branch
          githubRef=${{ env.githubRef }}
          dockerTag="latest"
        else
          # this run is for a PR
          githubRef=$githubHeadRef
          dockerTag="pull-${{ env.pullRequestNumber }}"
        fi

        # get branch name from ref
        branch=${githubRef##*/}

        echo "dockerTag=$dockerTag" >> $GITHUB_OUTPUT
        echo "branch=$branch" >> $GITHUB_OUTPUT
  build_app:
    name: build app
    runs-on: ubuntu-latest
    needs: [ initialize ]
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.githubRepository }}
          ref: ${{ needs.initialize.outputs.branch }}
          token: ${{ secrets.PAT }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Create Dockerfile
        working-directory: src
        run: |
          dockerfileText="FROM mcr.microsoft.com/dotnet/sdk:${{ inputs.baseImage }} AS build \n";
          dockerfileText="${dockerfileText}WORKDIR /app \n"
          dockerfileText="${dockerfileText}EXPOSE 80 \n\n"
          dockerfileText="${dockerfileText}COPY . ./ \n\n"
          dockerfileText="${dockerfileText}RUN dotnet publish "./${{ inputs.appName }}/${{ inputs.appName }}.csproj" \ \n"
          dockerfileText="${dockerfileText}-c Release \ \n"
          dockerfileText="${dockerfileText}-o /app/publish"
          
          if [ "${{ inputs.selfContained }}" = true ] ; then
            dockerfileText="${dockerfileText} \ \n"
            dockerfileText="${dockerfileText}--use-current-runtime \ \n"
            dockerfileText="${dockerfileText}--self-contained \ \n"
            dockerfileText="${dockerfileText}/p:PublishSingleFile=true \ \n"
            dockerfileText="${dockerfileText}/p:PublishTrimmed=true \n\n"
            dockerfileText="${dockerfileText}FROM mcr.microsoft.com/dotnet/runtime-deps:${{ inputs.baseImage }} \n\n"
            entrypoint="ENTRYPOINT ./${{ inputs.appName }}"
          else
            dockerfileText="${dockerfileText}FROM mcr.microsoft.com/dotnet/aspnet:${{ inputs.baseImage }} \n\n"
            entrypoint="ENTRYPOINT [\"dotnet\", \"${{ inputs.appName }}.dll\"]"
          fi

          dockerfileText="${dockerfileText}WORKDIR /app \n"
          dockerfileText="${dockerfileText}COPY --from=build /app/publish . \n"
          dockerfileText="${dockerfileText}${entrypoint}"
          
          echo -e "Dockerfile:"
          echo -e $dockerfileText

          echo -e $dockerfileText > Dockerfile
      -
        name: Build & push docker image
        timeout-minutes: 10
        working-directory: src
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

          sudo docker buildx create --name builder
          sudo docker buildx use builder

          sudo docker buildx build . \
            --file Dockerfile \
            --platform linux/amd64,linux/arm64 \
            --label commit=sha-${{ env.githubSha }} \
            -t ${{ inputs.dockerRepository }}:${{ needs.initialize.outputs.dockerTag }} \
            --push