name: Chart install

on:
  workflow_call:
    inputs:
      githubContext: # github context in JSON format
        required: true
        type: string
    secrets:
      PAT:
        required: true
      KUBECONFIG:
        required: true

jobs:
  install_chart:
    name: Install chart
    runs-on: ubuntu-latest
    steps:
      -
        name: Initialize chart info
        run: |
          # TODO delete branch
          githubRef=${{ fromJSON(inputs.githubContext).head_ref }}
          branch=${githubRef##*/}
          githubRepositoryName=$(basename ${{ fromJSON(inputs.githubContext).repository }})

          echo "branch=$branch" >> $GITHUB_ENV
          echo 'githubRepository=${{ fromJSON(inputs.githubContext).repository }}' >> $GITHUB_ENV
          echo "githubRepositoryName=$githubRepositoryName" >> $GITHUB_ENV
          echo 'githubSha=${{ fromJSON(inputs.githubContext).sha }}' >> $GITHUB_ENV
          echo 'workspace=${{ github.workspace }}' >> $GITHUB_ENV
      -
        name: Install helm
        run: |
          sudo snap install helm --classic
      -
        name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.githubRepository }}
          ref: ${{ env.branch }}
          token: ${{ secrets.PAT }}
      -
        name: Install chart
        working-directory: chart
        run: |
          touch kubeconfig
          echo '${{ secrets.KUBECONFIG }}' >> kubeconfig
          export KUBECONFIG=./kubeconfig

          helm repo add chartmuseum https://charts.pricegrabber.xyz
          helm repo update

          helm upgrade ${{ env.githubRepositoryName }} chartmuseum/universal-chart \
          --install \
          --namespace ${{ env.githubRepositoryName }} \
          --create-namespace \
          --wait \
          --version=1.0.0 \
          --values=./values.yaml

      # TODO future
      # - 
      #   name: Install chart
      #   uses: vimeda/helm@v1.6.8
      #   with:
      #     release: ${{ env.githubRepositoryName }}
      #     namespace: production
      #     version: ${{ env.githubSha }}
      #     value-files: ${{ env.workspace }}/chart/values.yaml
      #     chart: chartmuseum/universal-chart
      #     chart-version: 1.0.0
      #     repo: https://charts.pricegrabber.xyz
      #     repo-alias: chartmuseum
      #   env:
      #     KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'